version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Zipping Lambda function"
      - zip function.zip lambda/index.js

artifacts:
  files:
    - function.zip
    - appspec.yml
